#!/bin/bash
# ------------------------------------------------------------------------------
# Name: Script to install cPanel CDN Enabler.
# Sypnosis: afx-cppinstall ROOT_DIR
# Description: 
# Author: yclian
# Since: 2.4
# Version: 2.6.1.20100810
# ------------------------------------------------------------------------------

# Settings / Unit-Testable
# ------------------------------------------------------------------------------
set -x

# SOURCE_DIR, where the installation files are at.
if [ ! $SOURCE_DIR ]; then
    export SOURCE_DIR="$(dirname $0)/../.."
fi

# ROOT_DIR is typically '', hence, once appended with '/', it's your fs root.
# Hoever, for the sake of testability, $1 will be the sandbox location. 
export ROOT_DIR=$1
if [ ! $ROOT_DIR ]; then
    export ROOT_DIR=""
fi
export CPANEL_HOME="$ROOT_DIR/usr/local/cpanel"
export CPANEL_DATA="$ROOT_DIR/var/cpanel"

# The PHP executable used for running PHP scripts needed by this installation.
if [ ! $PHP_EXEC ]; then
    export PHP_EXEC="$(/bin/bash $(dirname $0)/php-getexec)"
fi

# YOU SHALL NOT BE TOUCHING ANYTHING DOWN HERE, ALTHOUGH YOU HAVE SUCH FREEDOM!
# ------------------------------------------------------------------------------

export CPANEL_BASE=$CPANEL_HOME/base
export CPANEL_FRONTEND=$CPANEL_BASE/frontend
export CPANEL_WHM=$CPANEL_HOME/whostmgr
export CPANEL_BIN=$CPANEL_HOME/bin
export CPANEL_AFX_HOME=$CPANEL_HOME/3rdparty/aflexi
export CPANEL_AFX_DATA=$CPANEL_DATA/aflexi

initialize_installation(){
    echo "Initializing installation.."
    bash "$(dirname $0)/pecl-installfix"
}

check_files(){
    
    echo "Checking installation files ($SOURCE_DIR).."

    if [[ ! -f "$SOURCE_DIR/LICENSE.txt" || 
	  ! -d "$SOURCE_DIR/common" || 
	  ! -d "$SOURCE_DIR/operator" || 
	  ! -d "$SOURCE_DIR/publisher" ||
	  ! -f "$SOURCE_DIR/publisher/cdn.cpanelplugin" ]]; then
    	echo "Some files are missing, have you set the SOURCE_DIR variable? Otherwise, please download again or contact support@aflexi.net." >&2
	    return 1
    fi
    
}

check_cpanel(){

    echo "Checking cPanel directories.."

    echo "cPanel directory: $CPANEL_HOME"
    echo "cPanel data: $CPANEL_DATA"

    if [[ ! -d $CPANEL_HOME || 
	    ! -d $CPANEL_DATA ]]; then
	echo "Some cPanel files are missing!" >&2
	return 1
    fi
    
}

check_perl(){
    bash "$(dirname $0)/perl-check"
    # NOTE [yclian 20100526] Currently there's no way (or I do not know) to de-
    # tect the exit code of Perl script executing the CPAN stuff.
    return $?
}

check_php(){
    bash "$(dirname $0)/php-check"
    return $?
}

prompt_license(){
    
    read -p "Do you agree with the above license [y/N]? "
    case "$REPLY" in
	[yY]) 
	    echo "Continuing installation.."
	    ;;
	[nN])
	    echo "Aborted!"
	    exit 0
	    ;;
	*)
	    prompt_license
    esac
}

initialize_dirs(){

    DIRS="$CPANEL_AFX_HOME,\
        $CPANEL_AFX_DATA,\
        $CPANEL_AFX_DATA/cache,\
        $CPANEL_AFX_DATA/cache/templates,\
        $CPANEL_AFX_DATA/operator,\
        $CPANEL_AFX_DATA/operator/cache,\
        $CPANEL_AFX_DATA/operator/cache/templates,\
        $CPANEL_WHM/docroot/3rdparty/aflexi,\
        $CPANEL_WHM/docroot/3rdparty/aflexi/web/images,\
        $CPANEL_WHM/docroot/3rdparty/aflexi/web/javascripts,\
        $CPANEL_WHM/docroot/3rdparty/aflexi/web/stylesheets,\
        $CPANEL_WHM/docroot/3rdparty/aflexi/web/templates,\
        $CPANEL_BASE/3rdparty/aflexi,\
        $CPANEL_BASE/3rdparty/aflexi/web/images,\
        $CPANEL_BASE/3rdparty/aflexi/web/javascripts,\
        $CPANEL_BASE/3rdparty/aflexi/web/stylesheets,\
        $CPANEL_BASE/3rdparty/aflexi/web/templates"
    
    echo "Initializing directories.."
    
    for DIR in `echo $DIRS | tr ',' '\n'`;
        do
            if [ ! -d $DIR ]; then
                mkdir -vp $DIR
            fi
        done;

    ln -vsf "$CPANEL_AFX_DATA/operator" "$CPANEL_AFX_DATA/whm"
}

copy_files(){

    echo "Copying files.."

    # Copy the common files first.
    cp -vrf $SOURCE_DIR/common/* $CPANEL_AFX_HOME &&
    
    # However, move the config files
    mv -vf $CPANEL_AFX_HOME/conf/* $CPANEL_AFX_DATA
    
    # exit 1
    
    
    # Add PHP 
    ln -vsf $PHP_EXEC $CPANEL_AFX_HOME/sbin/php &&
    
    copy_whm_files &&
    copy_frontend_files
    
    return $?
}

set_permissions(){
    # Execute is needed to access to dirs.
    chmod -vR 775 $CPANEL_AFX_DATA &&
    chmod -vR 777 $CPANEL_AFX_DATA/cache &&
    chmod -vR 770 $CPANEL_AFX_DATA/operator &&
    chmod -vR 770 $CPANEL_AFX_DATA/operator/cache
}

touch_files(){

    echo "Enabling CDN features and files.."
    
    bash "$(dirname $0)/afx-cppinstallfeature"
    # Write menus, etc.
}

copy_whm_files(){

    echo "Installing Aflexi WHM Add-On.."
    
    # whostmgr/docroot/3rdparty/aflexi
    cp -vrf $SOURCE_DIR/operator/* $CPANEL_WHM/docroot/3rdparty/aflexi &&
    ln -vsf $CPANEL_WHM/docroot/3rdparty/aflexi/web $CPANEL_WHM/docroot/aflexi &&
    ln -vsf $CPANEL_AFX_HOME/web/css $CPANEL_WHM/docroot/aflexi/css/base &&
    ln -vsf $CPANEL_AFX_HOME/web/img $CPANEL_WHM/docroot/aflexi/img/base &&
    ln -vsf $CPANEL_AFX_HOME/web/js $CPANEL_WHM/docroot/aflexi/js/base &&
    ln -vsf $CPANEL_AFX_HOME/web/templates $CPANEL_WHM/docroot/aflexi/templates/base &&
    ln -vsf $CPANEL_AFX_HOME/lib/main/AfxCpanel/Support/Php $CPANEL_WHM/docroot/aflexi/includes &&
    
    # The addon_cdn.cgi
    ln -vsf $CPANEL_WHM/docroot/3rdparty/aflexi/addon_cdn.cgi $CPANEL_WHM/docroot/cgi/addon_cdn.cgi &&
    chmod -v ug+x $CPANEL_WHM/docroot/cgi/addon_cdn.cgi
    
    return $?
}

copy_frontend_files(){

    echo "Installing Aflexi cPanel Plugin.."

    # base/3rdparty/aflexi
    cp -vrf $SOURCE_DIR/publisher/* $CPANEL_BASE/3rdparty/aflexi &&
    ln -vsf $CPANEL_BASE/3rdparty/aflexi/web $CPANEL_BASE/cdn &&
    ln -vsf $CPANEL_AFX_HOME/web/css $CPANEL_BASE/cdn/css/base &&
    ln -vsf $CPANEL_AFX_HOME/web/img $CPANEL_BASE/cdn/img/base &&
    ln -vsf $CPANEL_AFX_HOME/web/js $CPANEL_BASE/cdn/js/base &&
    ln -vsf $CPANEL_AFX_HOME/web/templates $CPANEL_BASE/cdn/templates/base &&
    ln -vsf $CPANEL_AFX_HOME/lib $CPANEL_BASE/cdn/includes &&
    
    if [ -d $CPANEL_BASE/frontend/x3 ]
        then
            ln -vsf $CPANEL_BASE/cdn $CPANEL_BASE/frontend/x3/cdn
            ln -vsf $CPANEL_BASE/cdn $CPANEL_BASE/frontend/x2/cdn
            ln -vsf $CPANEL_BASE/cdn $CPANEL_BASE/frontend/x/cdn
        else
            echo "Skipped! Default theme 'x3' seems missing."
    fi &&
    
    $CPANEL_BIN/register_cpanelplugin $SOURCE_DIR/publisher/cdn.cpanelplugin
    
    return $?
}

install_cron() {
    crontab -l > /tmp/crontab.aflexi.tmp

    DETECT=`grep 'Aflexi/CdnEnabler/Cpanel/Support/Php/cron.php' /tmp/crontab.aflexi.tmp`
    if [ !$DETECT ]; then
        echo "1-59/5 * * * * $CPANEL_AFX_HOME/lib/main/Aflexi/CdnEnabler/Cpanel/Support/Php/cron.php" >> /tmp/crontab.aflexi.tmp
    fi
    
    DETECT=`grep 'Aflexi/CdnEnabler/Cpanel/Support/Php/cronhour.php' /tmp/crontab.aflexi.tmp`
    if [ !$DETECT ]; then
        echo "17 * * * * $CPANEL_AFX_HOME/lib/main/Aflexi/CdnEnabler/Cpanel/Support/Php/cronhour.php" >> /tmp/crontab.aflexi.tmp
    fi
    
    cat /tmp/crontab.aflexi.tmp | crontab
    chmod a+x "$CPANEL_AFX_HOME/lib/main/Aflexi/CdnEnabler/Cpanel/Support/Php/cron.php"
    
    # ln -vsf "$CPANEL_AFX_HOME/lib/main/Aflexi/CdnEnabler/Cpanel/Support/Php/cron.php" "$ROOT_DIR/etc/cron.hourly/cron.php"
    # chmod a+x "$ROOT_DIR/etc/cron.hourly/cron.php"
}

check_error(){

    EXIT_CODE="$?"

    if [ $EXIT_CODE -gt 0 ]; then
        echo "Aborted! ($EXIT_CODE)"
        exit $EXIT_CODE
    fi
}

main(){
    
    initialize_installation &&
    check_files &&
    check_cpanel &&
    check_perl &&
    check_php
    
    check_error

    # Testing against sandbox will skip license check. 
    # YOU SHOULD NOT REMOVE THE FOLLOWING LICENSE PROMPT BLOCK FOR ANY POSSIBLE 
    # LEGAL REASONS - UNLESS LEGALLY APPOVED.
    if [ ! $CPANEL_SANDBOX ]; then
        less "$SOURCE_DIR/LICENSE.txt"
        prompt_license
    else
        echo "Skipped license prompt. Please read $SOURCE_DIR/LICENSE.txt if \
you are human."
    fi
    
    bash "$(dirname $0)/afx-cpppreupgrade"

    initialize_dirs &&
    copy_files &&
    set_permissions &&
    touch_files &&
    install_cron

    check_error

    echo "Installation successful!"
    exit 0
}

main

