#!/usr/bin/php
<?php

/**
 * PHP_VERSION_ID is available as of PHP 5.2.7, if our version is lower than that, then emulate it.
 *
 * @since 2.4
 * @version 2.4.20100520
 * @author yclian
 * @see http://php.net/manual/en/function.phpversion.php
 */
 
if (!defined('PHP_VERSION_ID')) {
    $version = explode('.', PHP_VERSION);

    define('PHP_VERSION_ID', ($version[0] * 10000 + $version[1] * 100 + $version[2]));
}

echo PHP_VERSION_ID

?>
